"""
Domain plugin: Symbolic Regression (1D number streams).

This is the simplest possible domain to validate the core loop.
Given (x, y) pairs generated by a mystery function, discover
the compositional formula.

This file implements all 4 interfaces for this domain.
It imports ONLY from core — no domain cross-contamination.
"""

from __future__ import annotations
import math
import random
import copy
from typing import Any

from core import (
    Environment, Grammar, DriveSignal,
    Primitive, Program, Task, Observation,
)


# =============================================================================
# Primitives: the atomic building blocks for symbolic math
# =============================================================================

def _safe_div(a, b):
    return a / b if abs(b) > 1e-10 else 0.0

def _safe_log(x):
    return math.log(abs(x)) if abs(x) > 1e-10 else 0.0

def _safe_sqrt(x):
    return math.sqrt(abs(x))

def _safe_exp(x):
    try:
        return math.exp(min(x, 20))
    except OverflowError:
        return 1e6

MATH_PRIMITIVES = [
    Primitive("x",      0, lambda ctx: ctx["x"]),
    Primitive("const",  0, lambda ctx: ctx.get("c", 1.0)),
    Primitive("add",    2, lambda a, b: a + b),
    Primitive("sub",    2, lambda a, b: a - b),
    Primitive("mul",    2, lambda a, b: a * b),
    Primitive("div",    2, _safe_div),
    Primitive("sin",    1, math.sin),
    Primitive("cos",    1, math.cos),
    Primitive("square", 1, lambda a: a * a),
    Primitive("cube",   1, lambda a: a * a * a),
    Primitive("sqrt",   1, _safe_sqrt),
    Primitive("log",    1, _safe_log),
    Primitive("exp",    1, _safe_exp),
    Primitive("neg",    1, lambda a: -a),
    Primitive("abs",    1, abs),
]

_PRIM_MAP = {p.name: p for p in MATH_PRIMITIVES}


# =============================================================================
# Environment: evaluate symbolic expressions on numeric data
# =============================================================================

class SymbolicMathEnv(Environment):

    def __init__(self):
        self._current_task = None

    def load_task(self, task: Task) -> Observation:
        self._current_task = task
        xs = [inp for inp, _ in task.train_examples]
        return Observation(data=xs, metadata={"task_id": task.task_id})

    def execute(self, program: Program, input_data: Any) -> Any:
        """Evaluate the expression tree on a single x value."""
        x_val = input_data
        return self._eval_tree(program, {"x": x_val})

    def reset(self):
        self._current_task = None

    def _eval_tree(self, node: Program, ctx: dict) -> float:
        prim = _PRIM_MAP.get(node.root)
        if prim is None:
            # It's a learned library entry — treat its children as the program
            # For now, return 0 (the grammar.inject_library should handle this)
            return 0.0

        if prim.arity == 0:
            if node.root == "const":
                ctx_with_c = {**ctx, "c": node.params.get("c", 1.0)}
                return prim.fn(ctx_with_c)
            return prim.fn(ctx)
        elif prim.arity == 1:
            child_val = self._eval_tree(node.children[0], ctx) if node.children else 0.0
            return prim.fn(child_val)
        elif prim.arity == 2:
            left = self._eval_tree(node.children[0], ctx) if len(node.children) > 0 else 0.0
            right = self._eval_tree(node.children[1], ctx) if len(node.children) > 1 else 0.0
            return prim.fn(left, right)
        return 0.0


# =============================================================================
# Grammar: composition rules for symbolic expressions
# =============================================================================

class SymbolicMathGrammar(Grammar):

    def __init__(self, seed: int = 42):
        self._rng = random.Random(seed)

    def base_primitives(self) -> list[Primitive]:
        return list(MATH_PRIMITIVES)

    def compose(self, outer: Primitive, inner_programs: list[Program]) -> Program:
        return Program(root=outer.name, children=inner_programs)

    def mutate(self, program: Program, primitives: list[Primitive]) -> Program:
        """Mutate a program: point (swap label), grow (leaf→subtree), or shrink (subtree→leaf).

        Point-only mutations can never change tree structure, so grow/shrink
        are essential for discovering programs that require different depths
        than the initial random beam provides.
        """
        prog = copy.deepcopy(program)
        nodes = self._collect_nodes(prog)
        if not nodes:
            return prog

        r = self._rng.random()
        if r < 0.25:
            # GROW: replace a leaf with a small subtree (adds depth)
            leaves = [n for n in nodes if not n.children]
            if leaves:
                target = self._rng.choice(leaves)
                # Pick a unary or binary primitive as new parent
                higher = [p for p in primitives if p.arity >= 1]
                if higher:
                    new_op = self._rng.choice(higher)
                    # Generate random leaf children
                    leaf_prims = [p for p in primitives if p.arity == 0]
                    if not leaf_prims:
                        leaf_prims = primitives
                    children = [
                        Program(root=self._rng.choice(leaf_prims).name)
                        for _ in range(new_op.arity)
                    ]
                    target.root = new_op.name
                    target.children = children
                    target.params = {}
            return prog
        elif r < 0.35:
            # SHRINK: replace a non-leaf subtree with a leaf (removes depth)
            internals = [n for n in nodes if n.children]
            if internals:
                target = self._rng.choice(internals)
                leaf_prims = [p for p in primitives if p.arity == 0]
                if leaf_prims:
                    new_leaf = self._rng.choice(leaf_prims)
                    target.root = new_leaf.name
                    target.children = []
                    target.params = {}
            return prog
        else:
            # POINT: swap label with same-arity primitive (preserves structure)
            target = self._rng.choice(nodes)
            prim = _PRIM_MAP.get(target.root)
            current_arity = prim.arity if prim else 0

            same_arity = [p for p in primitives if p.arity == current_arity]
            if same_arity:
                new_prim = self._rng.choice(same_arity)
                target.root = new_prim.name

            # Occasionally mutate a constant
            if target.root == "const":
                target.params["c"] = target.params.get("c", 1.0) + self._rng.gauss(0, 0.5)

            return prog

    def crossover(self, a: Program, b: Program) -> Program:
        """Replace a random subtree in a with a random subtree from b."""
        a_copy = copy.deepcopy(a)
        b_copy = copy.deepcopy(b)

        a_nodes = self._collect_nodes(a_copy)
        b_nodes = self._collect_nodes(b_copy)

        if not a_nodes or not b_nodes:
            return a_copy

        # Pick a random node in a to replace
        target = self._rng.choice(a_nodes)
        donor = self._rng.choice(b_nodes)

        # Overwrite target with donor
        target.root = donor.root
        target.children = donor.children
        target.params = donor.params

        return a_copy

    def _collect_nodes(self, program: Program) -> list[Program]:
        result = [program]
        for child in program.children:
            result.extend(self._collect_nodes(child))
        return result


# =============================================================================
# Drive Signal: MSE + complexity
# =============================================================================

class SymbolicMathDrive(DriveSignal):

    def prediction_error(self, predicted: Any, expected: Any) -> float:
        """Mean squared error for a single prediction."""
        if predicted is None or expected is None:
            return 1e6
        try:
            diff = float(predicted) - float(expected)
            return diff * diff
        except (TypeError, ValueError):
            return 1e6


# =============================================================================
# Task generator: create mystery function tasks
# =============================================================================

def make_task(
    fn,
    task_id: str = "mystery",
    n_train: int = 50,
    n_test: int = 20,
    x_range: tuple[float, float] = (0.0, 5.0),
    difficulty: float = 0.0,
) -> Task:
    """Generate a Task from a ground-truth function."""
    rng = random.Random(42)
    xs_train = [rng.uniform(*x_range) for _ in range(n_train)]
    xs_test = [rng.uniform(*x_range) for _ in range(n_test)]

    train = [(x, fn(x)) for x in xs_train]
    test_in = xs_test
    test_out = [fn(x) for x in xs_test]

    return Task(
        task_id=task_id,
        train_examples=train,
        test_inputs=test_in,
        test_outputs=test_out,
        difficulty=difficulty,
    )


# =============================================================================
# Quick demo: run the loop on a simple mystery function
# =============================================================================

if __name__ == "__main__":
    import logging
    import time
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    from core import Learner, InMemoryStore, SearchConfig, CurriculumConfig
    from core import WakeResult, extract_metrics, print_compounding_table

    print("=" * 70)
    print("  SYMBOLIC REGRESSION DEMO")
    print("  The same core algorithm discovers mathematical formulas")
    print("=" * 70)

    # Create tasks of increasing difficulty
    tasks = [
        make_task(lambda x: 2 * x + 1,               task_id="linear",    difficulty=1),
        make_task(lambda x: x ** 2,                   task_id="quadratic", difficulty=2),
        make_task(lambda x: math.sin(x) + x,          task_id="sin_plus_x", difficulty=3),
        make_task(lambda x: math.sin(x ** 2) + 2 * x, task_id="sin_x2_2x", difficulty=5),
    ]

    target_formulas = {
        "linear": "y = 2x + 1",
        "quadratic": "y = x²",
        "sin_plus_x": "y = sin(x) + x",
        "sin_x2_2x": "y = sin(x²) + 2x",
    }

    print(f"\n  Tasks ({len(tasks)} target functions to rediscover):")
    for t in tasks:
        print(f"    {t.task_id:<14s}  {target_formulas[t.task_id]:<25s}  (difficulty={t.difficulty})")
    print()

    # Wire up the 4 plugins
    env = SymbolicMathEnv()
    grammar = SymbolicMathGrammar(seed=42)
    drive = SymbolicMathDrive()
    memory = InMemoryStore()

    # Create the learner — the invariant core
    learner = Learner(
        environment=env,
        grammar=grammar,
        drive=drive,
        memory=memory,
        search_config=SearchConfig(
            beam_width=100,
            max_generations=80,
            energy_beta=0.001,
            solve_threshold=0.01,  # MSE < 0.01 counts as solved
            seed=42,
        ),
    )

    print(f"  Primitives:  {len(grammar.base_primitives())} "
          f"({', '.join(p.name for p in grammar.base_primitives())})")
    print(f"  Beam width:  100")
    print(f"  Generations: 80 per task")
    print(f"  Workers:     {Learner.performance_core_count()}")
    print()

    # Live progress callback
    t0 = time.time()

    def on_task_done(round_num, task_index, total_tasks, wr: WakeResult):
        elapsed = time.time() - t0
        icon = "✓" if wr.solved else "✗"
        energy_str = f"{wr.best.energy:.4f}" if wr.best else "N/A"
        prog_str = repr(wr.best.program) if wr.best else ""
        target = target_formulas.get(wr.task_id, "")
        print(f"  {icon} R{round_num} [{task_index}/{total_tasks}] "
              f"{wr.task_id:<14s} E={energy_str:<8s} "
              f"{wr.wall_time:.1f}s  [{elapsed:.0f}s elapsed]")
        if wr.solved:
            print(f"       target:  {target}")
            print(f"       found:   {prog_str}")

    # Run the curriculum
    results = learner.run_curriculum(
        tasks,
        CurriculumConfig(
            sort_by_difficulty=True,
            wake_sleep_rounds=3,
        ),
        on_task_done=on_task_done,
    )

    # Print the compounding curve
    print("\n" + "=" * 70)
    print("  COMPOUNDING CURVE — does solve rate increase across rounds?")
    print("=" * 70)
    metrics = extract_metrics(results)
    print_compounding_table(metrics)

    # Save library
    memory.save("library.json")
    print(f"\nLibrary entries: {len(memory.get_library())}")
    for entry in memory.get_library():
        print(f"  {entry.name}: {entry.program} (useful={entry.usefulness:.1f}, reused={entry.reuse_count}x)")
