"""
Domain plugin: Symbolic Regression (1D number streams).

This is the simplest possible domain to validate the core loop.
Given (x, y) pairs generated by a mystery function, discover
the compositional formula.

This file implements all 4 interfaces for this domain.
It imports ONLY from core — no domain cross-contamination.
"""

from __future__ import annotations
import math
import random
import copy
from typing import Any

from core import (
    Environment, Grammar, DriveSignal,
    Primitive, Program, Task, Observation,
)

try:
    from scipy.optimize import minimize as _scipy_minimize
    _HAS_SCIPY = True
except ImportError:
    _HAS_SCIPY = False


# =============================================================================
# Primitives: the atomic building blocks for symbolic math
# =============================================================================

def _safe_div(a, b):
    return a / b if abs(b) > 1e-10 else 0.0

def _safe_log(x):
    return math.log(abs(x)) if abs(x) > 1e-10 else 0.0

def _safe_sqrt(x):
    return math.sqrt(abs(x))

def _safe_exp(x):
    try:
        return math.exp(min(x, 20))
    except OverflowError:
        return 1e6

MATH_PRIMITIVES = [
    Primitive("x",      0, lambda ctx: ctx["x"]),
    Primitive("const",  0, lambda ctx: ctx.get("c", 1.0)),
    Primitive("add",    2, lambda a, b: a + b),
    Primitive("sub",    2, lambda a, b: a - b),
    Primitive("mul",    2, lambda a, b: a * b),
    Primitive("div",    2, _safe_div),
    Primitive("sin",    1, math.sin),
    Primitive("cos",    1, math.cos),
    Primitive("square", 1, lambda a: a * a),
    Primitive("cube",   1, lambda a: a * a * a),
    Primitive("sqrt",   1, _safe_sqrt),
    Primitive("log",    1, _safe_log),
    Primitive("exp",    1, _safe_exp),
    Primitive("neg",    1, lambda a: -a),
    Primitive("abs",    1, abs),
]

_PRIM_MAP = {p.name: p for p in MATH_PRIMITIVES}


# =============================================================================
# Constant optimization: fit coefficients for a fixed tree structure
# =============================================================================

def _collect_const_nodes(program: Program) -> list[Program]:
    """Return all 'const' leaf nodes in the tree (mutable references)."""
    result = []
    if program.root == "const":
        result.append(program)
    for child in program.children:
        result.extend(_collect_const_nodes(child))
    return result


def _eval_tree_raw(node: Program, x: float) -> float:
    """Evaluate a tree at a single x value (standalone, no Environment needed)."""
    prim = _PRIM_MAP.get(node.root)
    if prim is None:
        return 0.0
    if prim.arity == 0:
        if node.root == "const":
            return node.params.get("c", 1.0)
        return prim.fn({"x": x})
    elif prim.arity == 1:
        child_val = _eval_tree_raw(node.children[0], x) if node.children else 0.0
        return prim.fn(child_val)
    elif prim.arity == 2:
        left = _eval_tree_raw(node.children[0], x) if len(node.children) > 0 else 0.0
        right = _eval_tree_raw(node.children[1], x) if len(node.children) > 1 else 0.0
        return prim.fn(left, right)
    return 0.0


def optimize_constants(program: Program,
                       data: list[tuple[float, float]],
                       max_evals: int = 200) -> Program:
    """Fit the constant nodes in a program tree using scipy.

    Given a fixed tree structure, extracts all 'const' nodes, packs their
    values into a vector, minimizes MSE via Nelder-Mead, and writes the
    optimized values back.  Falls back to the original program if scipy
    is unavailable or optimization fails.

    Args:
        program: The expression tree (will be deep-copied).
        data: List of (x, y) training pairs.
        max_evals: Maximum function evaluations for the optimizer.

    Returns:
        A new Program with optimized constant values.
    """
    if not _HAS_SCIPY:
        return program

    prog = copy.deepcopy(program)
    const_nodes = _collect_const_nodes(prog)
    if not const_nodes:
        return prog  # nothing to optimize

    # Pack initial values
    x0 = [n.params.get("c", 1.0) for n in const_nodes]

    def objective(coeffs):
        # Write coefficients into the tree
        for node, val in zip(const_nodes, coeffs):
            node.params["c"] = val
        # Compute MSE
        total = 0.0
        for x, y in data:
            try:
                pred = _eval_tree_raw(prog, x)
                if not math.isfinite(pred):
                    return 1e12
                total += (pred - y) ** 2
            except Exception:
                return 1e12
        return total / len(data)

    try:
        result = _scipy_minimize(
            objective, x0, method="Nelder-Mead",
            options={"maxfev": max_evals, "xatol": 1e-8, "fatol": 1e-10},
        )
        # Write final values
        for node, val in zip(const_nodes, result.x):
            node.params["c"] = float(val)
    except Exception:
        pass  # keep original values on failure

    return prog


# =============================================================================
# Environment: evaluate symbolic expressions on numeric data
# =============================================================================

class SymbolicMathEnv(Environment):

    def __init__(self):
        self._current_task = None

    def load_task(self, task: Task) -> Observation:
        self._current_task = task
        xs = [inp for inp, _ in task.train_examples]
        return Observation(data=xs, metadata={"task_id": task.task_id})

    def execute(self, program: Program, input_data: Any) -> Any:
        """Evaluate the expression tree on a single x value."""
        x_val = input_data
        return self._eval_tree(program, {"x": x_val})

    def reset(self):
        self._current_task = None

    def _eval_tree(self, node: Program, ctx: dict) -> float:
        prim = _PRIM_MAP.get(node.root)
        if prim is None:
            # It's a learned library entry — treat its children as the program
            # For now, return 0 (the grammar.inject_library should handle this)
            return 0.0

        if prim.arity == 0:
            if node.root == "const":
                ctx_with_c = {**ctx, "c": node.params.get("c", 1.0)}
                return prim.fn(ctx_with_c)
            return prim.fn(ctx)
        elif prim.arity == 1:
            child_val = self._eval_tree(node.children[0], ctx) if node.children else 0.0
            return prim.fn(child_val)
        elif prim.arity == 2:
            left = self._eval_tree(node.children[0], ctx) if len(node.children) > 0 else 0.0
            right = self._eval_tree(node.children[1], ctx) if len(node.children) > 1 else 0.0
            return prim.fn(left, right)
        return 0.0


# =============================================================================
# Grammar: composition rules for symbolic expressions
# =============================================================================

class SymbolicMathGrammar(Grammar):

    def __init__(self, seed: int = 42, optimize_consts: bool = True):
        self._rng = random.Random(seed)
        self.optimize_consts = optimize_consts
        self._training_data: list[tuple[float, float]] = []

    def prepare_for_task(self, task: Task) -> None:
        """Cache training data for constant optimization during mutations."""
        self._training_data = list(task.train_examples)

    def base_primitives(self) -> list[Primitive]:
        return list(MATH_PRIMITIVES)

    def compose(self, outer: Primitive, inner_programs: list[Program]) -> Program:
        return Program(root=outer.name, children=inner_programs)

    def mutate(self, program: Program, primitives: list[Primitive],
               transition_matrix=None) -> Program:
        """Mutate a program: point (swap label), grow (leaf→subtree), or shrink (subtree→leaf).

        Point-only mutations can never change tree structure, so grow/shrink
        are essential for discovering programs that require different depths
        than the initial random beam provides.
        """
        prog = copy.deepcopy(program)
        nodes = self._collect_nodes(prog)
        if not nodes:
            return prog

        r = self._rng.random()
        if r < 0.25:
            # GROW: replace a leaf with a small subtree (adds depth)
            leaves = [n for n in nodes if not n.children]
            if leaves:
                target = self._rng.choice(leaves)
                # Pick a unary or binary primitive as new parent
                higher = [p for p in primitives if p.arity >= 1]
                if higher:
                    new_op = self._rng.choice(higher)
                    # Generate random leaf children
                    leaf_prims = [p for p in primitives if p.arity == 0]
                    if not leaf_prims:
                        leaf_prims = primitives
                    children = [
                        Program(root=self._rng.choice(leaf_prims).name)
                        for _ in range(new_op.arity)
                    ]
                    target.root = new_op.name
                    target.children = children
                    target.params = {}
            return prog
        elif r < 0.35:
            # SHRINK: replace a non-leaf subtree with a leaf (removes depth)
            internals = [n for n in nodes if n.children]
            if internals:
                target = self._rng.choice(internals)
                leaf_prims = [p for p in primitives if p.arity == 0]
                if leaf_prims:
                    new_leaf = self._rng.choice(leaf_prims)
                    target.root = new_leaf.name
                    target.children = []
                    target.params = {}
            return prog
        else:
            # POINT: swap label with same-arity primitive (preserves structure)
            target = self._rng.choice(nodes)
            prim = _PRIM_MAP.get(target.root)
            current_arity = prim.arity if prim else 0

            same_arity = [p for p in primitives if p.arity == current_arity]
            if same_arity:
                new_prim = self._rng.choice(same_arity)
                target.root = new_prim.name

            # Occasionally mutate a constant
            if target.root == "const":
                target.params["c"] = target.params.get("c", 1.0) + self._rng.gauss(0, 0.5)

            # Optimize constants after structural mutation
            if self.optimize_consts and self._training_data and _collect_const_nodes(prog):
                prog = optimize_constants(prog, self._training_data)

            return prog

    def crossover(self, a: Program, b: Program) -> Program:
        """Replace a random subtree in a with a random subtree from b."""
        a_copy = copy.deepcopy(a)
        b_copy = copy.deepcopy(b)

        a_nodes = self._collect_nodes(a_copy)
        b_nodes = self._collect_nodes(b_copy)

        if not a_nodes or not b_nodes:
            return a_copy

        # Pick a random node in a to replace
        target = self._rng.choice(a_nodes)
        donor = self._rng.choice(b_nodes)

        # Overwrite target with donor
        target.root = donor.root
        target.children = donor.children
        target.params = donor.params

        return a_copy

    def _collect_nodes(self, program: Program) -> list[Program]:
        result = [program]
        for child in program.children:
            result.extend(self._collect_nodes(child))
        return result


# =============================================================================
# Drive Signal: MSE + complexity
# =============================================================================

class SymbolicMathDrive(DriveSignal):

    def prediction_error(self, predicted: Any, expected: Any) -> float:
        """Mean squared error for a single prediction."""
        if predicted is None or expected is None:
            return 1e6
        try:
            diff = float(predicted) - float(expected)
            return diff * diff
        except (TypeError, ValueError):
            return 1e6


# =============================================================================
# Task generator: create mystery function tasks
# =============================================================================

def make_task(
    fn,
    task_id: str = "mystery",
    n_train: int = 50,
    n_test: int = 20,
    x_range: tuple[float, float] = (0.0, 5.0),
    difficulty: float = 0.0,
) -> Task:
    """Generate a Task from a ground-truth function."""
    rng = random.Random(42)
    xs_train = [rng.uniform(*x_range) for _ in range(n_train)]
    xs_test = [rng.uniform(*x_range) for _ in range(n_test)]

    train = [(x, fn(x)) for x in xs_train]
    test_in = xs_test
    test_out = [fn(x) for x in xs_test]

    return Task(
        task_id=task_id,
        train_examples=train,
        test_inputs=test_in,
        test_outputs=test_out,
        difficulty=difficulty,
    )


# =============================================================================
# Demo: the SAME core algorithm discovers mathematical formulas
# =============================================================================

if __name__ == "__main__":
    import logging
    import time
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    from core import Learner, InMemoryStore, SearchConfig, CurriculumConfig
    from core import WakeResult, extract_metrics, print_compounding_table

    _W = 72

    print()
    print("=" * _W)
    print("  SYMBOLIC REGRESSION — Formula Discovery Demo")
    print("=" * _W)
    print()
    print("  The challenge: given (x, y) data points from a mystery function,")
    print("  discover the symbolic formula that generated them.")
    print()
    print("  The approach: beam search over compositions of math primitives,")
    print("  with wake-sleep learning. The SAME core algorithm that solves")
    print("  ARC grid puzzles — only the primitives change.")
    print()
    print("─" * _W)
    print("  TARGET FORMULAS (what the algorithm must rediscover):")
    print("─" * _W)

    tasks = [
        make_task(lambda x: 2 * x + 1,               task_id="linear",    difficulty=1),
        make_task(lambda x: x ** 2,                   task_id="quadratic", difficulty=2),
        make_task(lambda x: math.sin(x) + x,          task_id="sin_plus_x", difficulty=3),
        make_task(lambda x: math.sin(x ** 2) + 2 * x, task_id="sin_x2_2x", difficulty=5),
    ]

    target_formulas = {
        "linear":     "y = 2x + 1",
        "quadratic":  "y = x²",
        "sin_plus_x": "y = sin(x) + x",
        "sin_x2_2x":  "y = sin(x²) + 2x",
    }

    for i, t in enumerate(tasks, 1):
        formula = target_formulas[t.task_id]
        n_train = len(t.train_examples)
        print(f"  {i}. {formula:<25s}  ({n_train} data points, difficulty={t.difficulty})")
    print()

    # Wire up the 4 interfaces — this is ALL a domain needs to provide
    env = SymbolicMathEnv()
    grammar = SymbolicMathGrammar(seed=42)
    drive = SymbolicMathDrive()
    memory = InMemoryStore()

    learner = Learner(
        environment=env,
        grammar=grammar,
        drive=drive,
        memory=memory,
        search_config=SearchConfig(
            beam_width=100,
            max_generations=80,
            energy_beta=0.001,
            solve_threshold=0.01,
            seed=42,
        ),
    )

    prims = grammar.base_primitives()
    print(f"  Building blocks: {len(prims)} primitives")
    print(f"    {', '.join(p.name for p in prims)}")
    print(f"  Search: beam_width=100, max_generations=80 per task")
    print(f"  Rounds: 3 wake-sleep cycles")
    print()

    # Track results per round for the summary
    round_results: dict[int, dict[str, str | None]] = {}
    t0 = time.time()

    def on_task_done(round_num, task_index, total_tasks, wr: WakeResult):
        elapsed = time.time() - t0
        icon = "✓" if wr.solved else "✗"
        target = target_formulas.get(wr.task_id, "")
        prog_str = repr(wr.best.program) if wr.best else ""

        if round_num not in round_results:
            round_results[round_num] = {}

        if wr.solved:
            round_results[round_num][wr.task_id] = prog_str
            print(f"  {icon}  {target:<25s} → {prog_str}")
        else:
            round_results[round_num][wr.task_id] = None
            energy_str = f"{wr.best.prediction_error:.4f}" if wr.best else "N/A"
            print(f"  {icon}  {target:<25s}    (best MSE: {energy_str})")

    # Run the curriculum
    for round_num in range(1, 4):
        lib_size = len(memory.get_library())
        print("─" * _W)
        print(f"  ROUND {round_num}/3   "
              f"(library: {lib_size} learned abstractions)")
        print("─" * _W)

    results = learner.run_curriculum(
        tasks,
        CurriculumConfig(sort_by_difficulty=True, wake_sleep_rounds=3),
        on_task_done=on_task_done,
    )
    total_time = time.time() - t0

    # Summary table
    print()
    print("=" * _W)
    print("  RESULTS — Compounding in Action")
    print("=" * _W)
    print()

    metrics = extract_metrics(results)

    # Show what was solved in each round
    for m in metrics:
        rn = m.round_number
        solved_count = m.tasks_solved
        total = m.tasks_total
        bar = "█" * solved_count + "░" * (total - solved_count)
        print(f"  Round {rn}:  {bar}  {solved_count}/{total} solved ({m.solve_rate:.0%})")

        if rn in round_results:
            for tid in ["linear", "quadratic", "sin_plus_x", "sin_x2_2x"]:
                result = round_results[rn].get(tid)
                if result:
                    print(f"           ✓ {target_formulas[tid]} → {result}")

    # Compounding curve
    if len(metrics) >= 2:
        first_rate = metrics[0].solve_rate
        last_rate = metrics[-1].solve_rate
        print()
        if last_rate > first_rate:
            print(f"  COMPOUNDING: {first_rate:.0%} → {last_rate:.0%} "
                  f"(+{last_rate - first_rate:.0%} from library growth)")
        elif last_rate == first_rate:
            print(f"  PLATEAU: solve rate stayed at {first_rate:.0%}")

    # Library
    lib = memory.get_library()
    if lib:
        print()
        print(f"  Library: {len(lib)} abstractions extracted during sleep")
        for entry in lib:
            print(f"    {entry.name}: {entry.program} "
                  f"(reused in {len(entry.source_tasks)} tasks)")

    print()
    print(f"  Total time: {total_time:.1f}s")
    print()
    print("  KEY INSIGHT: The same core algorithm (core/learner.py) runs this")
    print("  demo and ARC grid puzzles. Only the primitives differ.")
    print("  Try: python -m grammars.arc")
    print()
    print("=" * _W)
